Feat: Update documentation to describe project setup
lfit/github2gerrit pull request #20
Opened 2024-10-18 16:54 UTC by ModeSevenIndustrialSolutions

We need to be clear about the steps involved in setting this up for new projects at the LF. Happy to take comments on the additions in this PR.

2024-10-18 23:51 UTC, askb requested changes

2024-10-18 23:51 UTC, askb commented on README.md
> +## Deploying to a New Linux Foundation Project
Instead of having another section, please move these steps to pre-requisites (see ln 10+) above, there is already a well-maintained doc on how to create SSH keys and use them.  

https://docs.releng.linuxfoundation.org/en/latest/gerrit.html#register-key-gerrit

2024-10-18 23:51 UTC, askb commented on README.md
> +## Deploying to a New Linux Foundation Project
Please make this generic so that anyone outside of LF can follow the guide.

2024-10-18 23:53 UTC, askb commented
The PR tittle should be "Docs: ..." or "Fix: ..." instead of "Feat: ..."

2024-10-21 13:35 UTC, ModeSevenIndustrialSolutions commented on README.md
> +## Deploying to a New Linux Foundation Project
Perhaps this should simply be documented on the LF RelEng Confluence Wiki instead? There are concrete steps needed to set this up for LF projects that are NOT for general consumption, which are currently missing. If you want generic documentation, perhaps our internal docs should go elsewhere.

2024-10-21 13:37 UTC, ModeSevenIndustrialSolutions commented on README.md
> +## Deploying to a New Linux Foundation Project
e.g. [https://linuxfoundation.atlassian.net/wiki/spaces/RELEN/pages/190021675/Gerrit+to+platform+for+Github+Actions](https://linuxfoundation.atlassian.net/wiki/spaces/RELEN/pages/190021675/Gerrit+to+platform+for+Github+Actions)

2024-10-21 13:43 UTC, ModeSevenIndustrialSolutions commented
Moved here:
[https://linuxfoundation.atlassian.net/wiki/spaces/RELEN/pages/286130178/GitHub2Gerrit](https://linuxfoundation.atlassian.net/wiki/spaces/RELEN/pages/286130178/GitHub2Gerrit)

2024-10-21 13:43 UTC, closed without merging