Feat: Add support single commits and PR body and tittle as commit message
lfit/github2gerrit pull request #4
Opened 2024-08-01 09:57 UTC by askb

- Each commit in the pull request is processed individually as a
  single commit before submitting to Gerrit repository. This option
  allows you to preserve git history. This requires `inputs.SUBMIT_SINGLE_COMMITS` to be set to 'true'
  from the caller.
  
- Remove extra inputs. Gerrit server and port and the project must be read
  from .gitreview file. Composite actions are limited on
  the number of inputs that can be passed to 10.

- Support USE_PR_AS_COMMIT flag, allows commit message to be
  replaced the pull request body and title.
  Note: the 50/72 rule of the title and body needs to be taken
  care of by the developer or the pre-commit verification would fail.

- Comment the PR URL link along with the workflow run URL on the
  Gerrit change request using `ssh gerrit review` CLI. This is
  useful to Jenkins jobs to query comments on the change and search
  for PR-### URL therefore allow developer comments to be sync back
  to the pull request on Github.

- Prefix the git-review topic with the project name followed by
  PR-### to ensure the same topic is not overused from different projects
  under the same organization.

- Update docs and examples caller workflows accordingly.

2024-08-06 23:05 UTC, tykeal requested changes
Minor typo in the first commit along with a note on future feature needs

2024-08-07 00:37 UTC, askb commented on README.md
> +6. Close the pull request once the Gerrit patch is submitted. A comment is added to the pull request with the URL to the change. Any updates will require the pull request to be reopened. Updates to t
I have not reused change-id's while test this on sandbox which has resulted in a few abandoned commits. :)

The workflow handles the PR re-open as follows:
1. The change-id exist on Gerrit and is NOT abandoned and open: 
    a. when the commit on git uses the same change-id: then same change gets updated 
    b. when the commit on git does NOT use the same change-id: new change gets created (upto dev to ensure the same change-id us reused)  
c. when the commit on git uses a NEW change-id: new change gets created (upto dev to ensure the same change-id us reused) 
2. The change-id exist on Gerrit and is abandoned or closed: git-review returns an error on change-id reused incorrectly. 

A little care needs to taken while updating the change, I think this can be acheived seemlessly once Gerrit comments are in Sync with Github PR with the ability to post a comment.

2024-08-07 01:08 UTC, askb reviewed
Update the review comments and fixed the type. Thanks for the review.

2024-08-14 22:42 UTC, tykeal approved these changes

2024-08-14 22:43 UTC, merged